export const TOPICS = [
  { label: 'Find a car', match: /\b(book|booking|rent|car|available|availability|vehicle)\b/i, text: 'Choose pickup and return dates in Explore cars, then filter by name, fuel, seats or hourly price. Open View & Book to review your trip. Sign in to confirm a reservation.', href: '/', action: 'Explore cars' },
  { label: 'Pricing', match: /\b(price|pricing|cost|fee|charge|cheap|budget|hour|expensive)\b/i, text: 'Rental hours are rounded up to the next whole hour. The total is hourly rent × hours, plus an optional driver at ₹30/hour, then a 3% service fee on that subtotal. Your checkout shows the exact total.', href: '/', action: 'Compare hourly rates' },
  { label: 'Payments', match: /\b(pay|payment|payments|card|stripe|upi|cash)\b/i, text: 'Pay at Pickup is available: reserve now and pay when collecting the car. Online card payments are not currently available. I cannot process a payment or check your bank account.', href: '/userbookings', action: 'View my bookings' },
  { label: 'Cancel a trip', match: /\b(cancel|cancellation|refund|cancelled)\b/i, text: 'Open My Bookings and select Cancel Booking on an eligible reservation before pickup. Review the confirmation before cancelling. I cannot cancel bookings or verify refunds for you.', href: '/userbookings', action: 'Manage my bookings' },
  { label: 'List my car', match: /\b(list|listing|host|owner|earn|earnings|payout)\b/i, text: 'Open List Your Car, add the vehicle details and photos, and submit for review. Approval is required before your listing appears. Check My Listings for its status; earnings are shown in your owner dashboard.', href: '/list-your-car', action: 'List your car' },
  { label: 'Driver option', match: /\b(driver|chauffeur|self.drive)\b/i, text: 'The booking page offers an optional driver for ₹30 per rental hour. Select the driver option to include it in your price breakdown before confirming.', href: '/', action: 'Choose a vehicle' },
];
export function answerQuestion(question) {
  if (/\b(human|contact|support|emergency|accident|phone)\b/i.test(question)) return { text: 'This is an automated rental guide, not a live support agent. I cannot contact staff or handle emergencies. For a reservation issue, open your booking details and use any contact information provided there. For immediate danger, contact local emergency services.', href: '/userbookings', action: 'Open booking details' };
  return [...TOPICS.slice(1), TOPICS[0]].find(topic => topic.match.test(question)) || { text: 'I can help with finding a car, rental pricing, payments, cancellations, driver options, and listing your car. Try one of the topics below. I cannot access your account or make changes on your behalf.' };
}
